[build]
builder = "NIXPACKS"

[nixpacks]
packages = [
  "libsodium",      # encryption
  "libopus",        # opus encoder cho voice
  "opusTools",      # hỗ trợ thêm cho play-dl
  "ffmpeg"          # stream audio
]

[env]
NODE_VERSION = "20"

[phases.install]
cmds = ["npm install"]
